runtime: nodejs18
env: standard
instance_class: F2
automatic_scaling:
  max_instances: 1
  min_instances: 0
env_variables:
  BUCKET_NAME: "talenthub_central"
  ROOT_FOLDER_ID: "1PcnN9zwjl9w_b9y99zS6gKWMhwIVdqfD"