steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/drive-to-gcs-sync', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/drive-to-gcs-sync']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'drive-to-gcs-sync'
    - '--image'
    - 'gcr.io/$PROJECT_ID/drive-to-gcs-sync'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--memory'
    - '1Gi'
    - '--set-env-vars'
    - 'BUCKET_NAME=${_BUCKET_NAME},ROOT_FOLDER_ID=${_ROOT_FOLDER_ID}'

images:
  - 'gcr.io/$PROJECT_ID/drive-to-gcs-sync'