steps:
# Build usando el Dockerfile explícitamente
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '-t', 'gcr.io/$PROJECT_ID/drive-sync', 
         '-f', 'src/Dockerfile',  # ← Usa el Dockerfile de src/
         'src/']  # ← Contexto es la carpeta src/

# Push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/drive-sync']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'drive-sync'
  - '--image=gcr.io/$PROJECT_ID/drive-sync'
  - '--region=europe-west1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--set-env-vars=BUCKET_NAME=talenthub_central,ROOT_FOLDER_ID=1PcnN9zwjl9w_b9y99zS6gKWMhwIVdqfD'
  - '--memory=512Mi'
  - '--cpu=1'

images:
- 'gcr.io/$PROJECT_ID/drive-sync'